### ISSUE TITLE
Bug when running code on a windows system.

### ISSUE THREAD

**Issue by PopeSpaceous** [cjlcarvalho/crazy-robots#9]
Hi, 
I noticed when running the code on a windows system that the system("clear"); doesn't work and prints an error.
I propose adding a systems check at the beginning to check what OS it is running on. Then using "clear" if on unix based system, or "CLS" on a windows system. 

I would like to work on this issue. 
Thanks.

**Comment by cjlcarvalho** [comment]
@PopeSpaceous You can just use ifdef to check if __WIN32__ has been defined. If it is, then you print using "cls", else you print "clear". Feel free to submit a pull request.
